
# Other Homebrew packages
brew autoconf
brew awscli
brew brew-file
brew cmake
brew ctop
brew curl
brew direnv
brew ethereum
brew gdbm
brew gettext
brew git
brew htop
brew hub
brew icu4c
brew jq
brew libffi
brew llvm
brew mas
brew ncurses
brew node
brew node-build
brew nodenv
brew oniguruma
brew openssl
brew openssl@1.1
brew pcre
brew pcre2
brew pkg-config
brew python
brew readline
brew rustup-init
brew sqlite
brew swig
brew telnet
brew tig
brew tree
brew xz
brew yarn
brew z
brew zsh
brew zsh-completions

# Other Cask applications
cask 1password
cask alfred
cask astropad
cask discord
cask docker
cask evernote
cask ganache
cask github
cask google-chrome
cask google-japanese-ime
cask iterm2
cask slack
cask visual-studio-code

# App Store applications
appstore 408981434 iMovie (10.1.12)
appstore 409183694 Keynote (9.1)
appstore 539883307 LINE (5.19.0)
appstore 497799835 Xcode (10.3)
